### PR TITLE
Fix publication link, minor change in load matrix function

### PR DESCRIPTION
**Pull request by titipata**
Hello @MrChrisJohnson, I update 2 things to the repository
- publication link in `README` (seems like author change the link)
- minor change in `load_matrix` function so that we don't have to create dense matrix at the beginning.

### CODE REVIEW

**Comment by MrChrisJohnson** [comment]
Looks good to me. Has this been tested?

**Comment by titipata** [comment]
Yeah, I tested the function :) Thanks for merging @MrChrisJohnson!

**Comment by titipata** [comment]
@MrChrisJohnson maybe you want to change link on top of the repository too.

**Comment by MrChrisJohnson** [comment]
Just fixed. Thanks.

**Pull request merged**
